package objetos;
    public class Carro {

        private String marca;
        private String modelo;
        private int ano;
        private String cor;


        // Getters e Setters
        public String getMarca() {
            return marca;
        }

        public String getModelo() {
            return modelo;
        }

        public int getAno() {
            return ano;
        }


        public String getCor() {
            return cor;
        }

        public void setMarca(String marca) {
            this.marca = marca;
        }

        public void setModelo(String modelo) {
            this.modelo = modelo;
        }

        public void setAno(int ano) {
            this.ano = ano;
        }

        public void setCor(String cor) {
            this.cor = cor;
        }

    }
